name: lys
description: Application to control RGB LED Strip by sending HTTP requests to a webserver running on an Arduino.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.3+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: # TODO: Sort this alphabetically??
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^2.1.1
  dartz: ^0.10.1
  provider: ^6.0.4
  badges: ^2.0.3
  animated_theme_switcher: "^2.0.5"
  adaptive_navigation: ^0.0.7
  dio: ^4.0.6
  freezed: ^2.3.2
  json_annotation: ^4.7.0
  flutter_adaptive_scaffold: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3
  lint: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
